# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'vs2017-win2016'

name: $(Date:yyyyMMdd)$(rev:.rr)

variables:
  imageName: 'msbuild:$(Build.BuildNumber)'

steps:
  - script: docker build --file Dockerfile --tag $(AcrId).azurecr.io/$(imageName) .
    displayName: 'docker build'

  - script:
      docker login --username $(AcrId) --password $(Password) $(AcrId).azurecr.io
    displayName: 'docker login'

  - script:
      docker push $(AcrId).azurecr.io/$(imageName)
    displayName: 'docker push'
